= Blobs
:page-aliases:
:page-layout: article
:page-role:
:description: Couchbase Lite database data model concepts - blobs

:source-language: javascript

[abstract]
--
Description -- _{description}_ +
Related Content -- xref:database.adoc[Databases] | xref:document.adoc[Documents] | xref:indexing.adoc[Indexing] |
--

[#introduction]
== Introduction

Couchbase{nbsp}Lite for JavaScript uses _blobs_ to store the contents of images, other media files and similar format files as binary objects.

The blob itself is not stored in the document.
It is held in a separate content-addressable store indexed from the document and retrieved only on-demand.

When a document is synchronized, the Couchbase{nbsp}Lite replicator adds an `_attachments` dictionary to the document's properties if it contains a blob.

[#blob-objects]
== Blob Objects

The blob as an object appears in a document as a dictionary property.

Other properties include `length` (the length in bytes), and optionally `contentType` (typically, its MIME type).

The blob's data (an image, audio or video content) is not stored in the document, but in a separate content-addressable store, indexed by the `digest` property -- see xref:blob.adoc#lbl-using[].

[#constraints]
=== Constraints

* Couchbase{nbsp}Lite +
Blobs can be arbitrarily large.
They are only read on demand, not when you load the _document_.

* Sync{nbsp}Gateway +
The maximum content size is 20 MB per blob.
If a document's blob is over 20 MB, the document will be replicated but not the blob.

[#lbl-using]
== Using Blobs

The `Blob` class in Couchbase Lite JavaScript provides methods to work with binary data.
You can create blobs from various sources including File objects, ArrayBuffers, or URLs.

The code in xref:blob.adoc#ex-blob[] shows how you might add a blob to a document and save it to the database. Here we use `avatar` as the property key and an image file as the blob data.

.Working with blobs
[#ex-blob]

====

[source, javascript]
----
include::example$code_snippets/code_snippets.ts[tags="using-blobs", indent=0]
----

====

<.> Here we prepare a document to use for the example
<.> Create the blob from a File object (from a file input or drag-and-drop). +
 Here we set `image/jpeg` as the blob MIME type.
<.> Add the blob to a document, using `avatar` as the property key +
Saving the document generates a random access key for each blob stored in `digest`, a SHA-1 encrypted property -- see: xref:blob.adoc#img-blob[]. +
We can use the `avatar` key to retrieve the blob object later.
Note, this is the identity of the blob assigned by us; the replication auto-generates a blob for attachments and assigns its own name to it (for example, `blob_1`) -- see xref:blob.adoc#img-blob[].
The `digest` key will be the same as generated when we saved the blob document.

[#creating-blobs]
== Creating Blobs

You can create blobs from different sources in the browser:

[#from-file-input]
=== From File Input

.Create blob from file input
[#ex-blob-file-input]

====

[source, javascript]
----
include::example$code_snippets/code_snippets.ts[tags="creating-blobs-file-input", indent=0]
----

====

[#from-fetch]
=== From Fetch API

.Create blob from fetched data
[#ex-blob-fetch]

====

[source, javascript]
----
include::example$code_snippets/code_snippets.ts[tags="blob-fetch", indent=0]
----

====

////
[#from-arraybuffer]
=== From ArrayBuffer

.Create blob from ArrayBuffer
[#ex-blob-arraybuffer]

====

[source, javascript]
----
include::example$code_snippets/code_snippets.ts[tags="blob-arraybuffer", indent=0]
----

====
////

[#retrieving-blobs]
== Retrieving Blobs

Once a blob is saved in a document, you can retrieve it and access its content.

.Retrieve and use blob
[#ex-blob-retrieve]

====

[source, javascript]
----
include::example$code_snippets/code_snippets.ts[tags="blob-retrieve", indent=0]
----

====

[#blob-properties]
== Blob Properties

Blob objects have several properties that provide information about the binary data:

* `contentType` - The MIME type of the blob (e.g., "image/jpeg", "video/mp4")
* `length` - The size of the blob in bytes
* `digest` - The SHA-1 hash of the content, used for content-addressable storage
* `properties` - Additional metadata stored with the blob

.Access blob properties
[#ex-blob-properties]

====

[source, javascript]
----
include::example$code_snippets/code_snippets.ts[tags="blob-properties", indent=0]
----

====

[#typescript-blobs]
== TypeScript Support

When using TypeScript, you can define document interfaces that include blob properties:

.Type-safe blobs
[#ex-typescript-blob]

====

[source, typescript]
----
include::example$code_snippets/code_snippets.ts[tags="typescript-blob", indent=0]
----

====

[#syncing]
== Syncing

When a document containing a blob object is synchronized, the Couchbase{nbsp}Lite replicator generates an `_attachments` dictionary with an auto-generated name for each blob attachment.
This is different to the `avatar` key and is used internally to access the blob content.


[#blob-metadata]
== Blob Metadata

Blobs in Couchbase Lite follow a specific metadata structure that allows the system to identify and retrieve binary content:

.Blob metadata structure
[source, json]
----
{
  "@type": "blob",
  "content_type": "image/jpeg",
  "length": 45678,
  "digest": "sha1-s1KdHLHCQqn/34fFxZqQRMHrQGk="
}
----

The `@type` property identifies this object as a blob rather than a regular nested object.
The replicator uses this metadata to handle blob synchronization separately from document data.

[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
=== {empty}
.How to . . .
* xref:gs-prereqs.adoc[Prerequisites]
* xref:gs-install.adoc[Install]

.

[.column]
=== {empty}
.Learn more . . .
* xref:database.adoc[Databases]
* xref:document.adoc[Documents]
* xref:blob.adoc[Blobs]
* xref:replication.adoc[Remote Sync Gateway]
* xref:conflict.adoc[Handling Data Conflicts]

.

[.column]
=== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++