= Installing Couchbase Lite JavaScript
:page-aliases:
:page-role:
:description: How to install Couchbase Lite JavaScript
:keywords: edge nosql api JavaScript TypeScript browser web npm

:source-language: JavaScript

[abstract]
--
Description -- _{description}_ +
_Abstract -- Getting you up and running quickly with Couchbase Lite JavaScript_ +
--

[#introduction]
== Introduction

Couchbase Lite JavaScript is distributed as an npm package and supports development in both JavaScript and TypeScript.

[#installation]
== Installation

Add Couchbase Lite JavaScript to your web application project using npm:

[source,bash, subs="attributes+"]
----
npm install @couchbase/lite-js
----

Then import Couchbase Lite in your JavaScript/TypeScript code:

[source,javascript]
----
import { Database, Replicator } from '@couchbase/lite-js';
----

That's it! You're all set to begin developing offline-first web applications.

[#verify-installation]
== Verify Installation

After installing, verify that Couchbase Lite is correctly installed.

[#check-import]
=== Verify Import

Create a simple test file:

[source,javascript]
----
// test.js
import { Database, Version } from '@couchbase/lite-js';

console.log('Couchbase Lite version:', Version);
----

[#basic-functionality-test]
=== Test Basic Functionality

Test creating a database:

[source,javascript]
----
import { Database } from '@couchbase/lite-js';

async function test() {
  try {
    const db = await Database.open('test-db', {
      name: 'test-db',
      version: 1,
      collections: {
      items: {}
      }
    });

    console.log('✓ Database created successfully');

    await db.close();
    console.log('✓ Database closed successfully');

    // Clean up
    await Database.deleteDatabase('test-db');
    console.log('✓ Database deleted successfully');

  } catch (error) {
    console.error('✗ Installation test failed:', error);
  }
}

test();
----


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:gs-prereqs.adoc[Prerequisites]
* xref:gs-install.adoc[Install]

.

[.column]
====== {empty}
.Learn more . . .
* xref:database.adoc[Databases]
* xref:document.adoc[Documents]
* xref:blob.adoc[Blobs]
* xref:replication.adoc[Remote Sync Gateway]
* xref:conflict.adoc[Handling Data Conflicts]

.

[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++