= Installing Couchbase Lite JavaScript
:page-aliases:
:page-role:
:description: How to install Couchbase Lite JavaScript
:keywords: edge nosql api JavaScript TypeScript browser web npm

:source-language: JavaScript

[abstract]
--
Description -- _{description}_ +
_Abstract -- Getting you up and running quickly with Couchbase Lite JavaScript_ +
--

[#introduction]
== Introduction

Couchbase Lite JavaScript is distributed as an npm package and supports development in both JavaScript and TypeScript.

[#installation]
== Installation

Add Couchbase Lite JavaScript to your web application project using npm:

[source,bash, subs="attributes+"]
----
npm install @couchbase/lite-js
----

Then import Couchbase Lite in your JavaScript/TypeScript code:

[source,javascript]
----
include::example$code_snippets/code_snippets.ts[tags="imp-database;imp-replicator", indent=0]
----

That's it! You're all set to begin developing offline-first web applications.

[#verify-installation]
== Verify Installation

After installing, verify that Couchbase Lite is correctly installed.

[#check-import]
=== Verify Import

Create a simple test file:

[source,javascript]
----
include::example$code_snippets/code_snippets.ts[tags="gs-test-file-label;imp-database;imp-version;imp-gap;gs-verify-version", indent=0]
----

[#basic-functionality-test]
=== Test Basic Functionality

Test creating a database:

[source,javascript]
----
include::example$code_snippets/code_snippets.ts[tags="imp-database;imp-gap;gs-basic-test", indent=0]
----


[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:gs-prereqs.adoc[Prerequisites]
* xref:gs-install.adoc[Install]

.

[.column]
====== {empty}
.Learn more . . .
* xref:database.adoc[Databases]
* xref:document.adoc[Documents]
* xref:blob.adoc[Blobs]
* xref:replication.adoc[Remote Sync Gateway]
* xref:conflict.adoc[Handling Data Conflicts]

.

[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++