= Preparing for Couchbase Lite JavaScript
:page-aliases:
:page-role:
:description: Prerequisites for the installation of Couchbase Lite JavaScript
:keywords: edge nosql api JavaScript TypeScript browser web

:source-language: JavaScript

[abstract]
--
Description -- _{description}_ +
_Abstract -- Laying out the prerequisites and preparatory steps before installing Couchbase Lite JavaScript_ +
--

[#browser-compatibility]
== Browser Compatibility

The Couchbase Lite JavaScript SDK is compatible with all major modern browsers, including Safari, Chrome, Firefox, and Microsoft Edge, across both desktop and mobile platforms. It uses IndexedDB as the underlying storage engine to ensure reliable offline persistence and performance.

Compatibility has been verified on the following browser versions (and newer):

* Safari 17+
* Chrome 142+
* Firefox 144+

NOTE: Sync behaviour may be limited in private browsing modes (especially Chrome).

The SDK also runs seamlessly in Progressive Web App (PWA) environments, enabling installable, native-like usage scenarios.

[#prerequisites]
== Prerequisites

A modern ES2022+ JavaScript environment is needed for execution as the SDK uses promises and async/await features. Node.js 22+ is also required for development and build tooling.

If you are using Sync Gateway or App Services as a backend for your browser-based applications, you should enable CORS before you can synchronize data:

* For App Services, see https://docs.couchbase.com/cloud/app-services/deployment/cors-configuration-for-app-services.html[CORS Configuration for App Services]
* The CORS configuration should be done in the xref:4.0@sync-gateway:configuration:configuration-schema-bootstrap.adoc#lbl-schema[Sync Gateway Bootstrap Configuration].

[#related-content]
== Related Content
++++
<div class="card-row three-column-row">
++++

[.column]
====== {empty}
.How to . . .
* xref:gs-prereqs.adoc[Prerequisites]
* xref:gs-install.adoc[Install]

.

[.column]
====== {empty}
.Learn more . . .
* xref:database.adoc[Databases]
* xref:document.adoc[Documents]
* xref:blob.adoc[Blobs]
* xref:replication.adoc[Remote Sync Gateway]
* xref:conflict.adoc[Handling Data Conflicts]

.

[.column]
====== {empty}
.Dive Deeper . . .
https://forums.couchbase.com/c/mobile/14[Mobile Forum] |
https://blog.couchbase.com/[Blog] |
https://docs.couchbase.com/tutorials/[Tutorials]

.

++++
</div>
++++